### ISSUE TITLE
Config file loading does not respect CLI verbosity settings

### ISSUE THREAD

**Issue by anjos** [idiap/clapper#5]
I have an issue whereby an app in my package (say `pkg.app`) receives a configuration file (say `pkg.config1`), which constructs a complex object inside.  During construction, a log message (type INFO) may be issued.

Problem: For some reason, this log message is never printed to the screen, even if I increase the verbosity level of my app.

I suspect this stems from the fact that the config file is loaded using a different namespace (other than `pkg`), and therefore the CLI verbosity setting can never affect it properly.  I could modify the verbosity setting to affect the root logger, but that would open a can of worms.

Is there a way I could set the verbosity level correctly in `pkg.app` so that both messages from `pkg` and eventual configuration files loaded are correctly respecting the app's verbosity setting?

**Comment by Yannick-Dayer** [comment]
I noticed that variables like `__file__` are not defined when accessing them from config files.
I dug a bit and, as you suggest, the config files are loaded in a separate context ([with `exec`](https://github.com/idiap/clapper/blob/944ea459643364587b8260970696de9150a38919/src/clapper/config.py#L52)).

I'll look for a solution to have the logger set correctly in the config files.

**Comment by Yannick-Dayer** [comment]
The logger level is set by `clapper.click.verbosity_option` and the configs are loaded before the logger's level is set to the wanted value.

I'm looking for a way to handle the verbosity option first.

Until then, you could set the configs log level by "hard coding" it:

```python
# dummy/app.py

import clapper.click
import clapper.logging
import click

logger = clapper.logging.setup("dummy")  # top-level / package name
logger.setLevel("INFO") # This will be the level in the config files

@click.command(
    entry_point_group="func_group",
    cls=clapper.click.ConfigCommand,
)
@click.option(
    "--conf",
    "-c",
    "conf_param",
    entry_point_group="config_group",
    cls=clapper.click.ResourceOption,
)
@clapper.click.verbosity_option(logger)
def fun1(conf_param: str, **kwargs):
    pass

```

and 

```python
# dummy/config.py

import logging

logger = logging.getLogger(__name__)
print(f"got logger for {__name__=}: {logger}")
```

**Comment by anjos** [comment]
Right - yes, I can see that this one is tricky.
