### ISSUE TITLE
Adding a formatter option

### ISSUE THREAD

**Issue by anjos** [idiap/clapper#8]
It would be great to have colored output for logs.  I'm not sure how to best implement this without being opinionated on colors.

A possible solution to avoid increasing the number of dependencies would be if the `setup()` method from `clapper` accepted a formatter as explained here: https://stackoverflow.com/a/37895226/712525.

This would allow users to add any color logging implementation of their choice, w/o implying changes to this package's dependencies.

**Comment by Yannick-Dayer** [comment]
I agree. Allowing to specify a formatter could be a good way of providing more flexibility in the output format. And it should not be too much trouble integrating it in `click.logging.setup`.
